version: 0.2
env:
  variables:
    REPOSITORY_URI: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
phases:
  install:
    runtime-versions: 
      docker: 20
    commands:
      - echo Installing kubectl...
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - echo Successfully installed kubectl
      - sudo ~/kubectl version --client
      - echo Installing authenticator...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Setting up Kubernetes context...
      - aws eks update-kubeconfig --name my-eks-cluster --region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Building the Docker image...
      - pwd 
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME $REPOSITORY_URI
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI
      - cat deployment.yaml
      - sudo kubectl config view 
      - echo Applying deployment...
      - sudo kubectl apply -f deployment.yaml
artifacts:
  files:
    - '**/*'
  discard-paths: yes
